import js from '@eslint/js';
import prettier from 'eslint-config-prettier';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'node_modules',
      'supabase/.branches',
      'supabase/.temp',
      // Edge Functions are Deno, not browser TypeScript: different globals,
      // different module resolution, checked by `deno check` instead.
      'supabase/functions',
      // Generated by `supabase gen types`. Linting it only means re-fixing the
      // same findings after every regeneration.
      'src/shared/types/database.types.ts',
    ],
  },

  // ── Application source ────────────────────────────────────────────────────
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommendedTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        project: ['./tsconfig.app.json'],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-misused-promises': [
        'error',
        { checksVoidReturn: { attributes: false } },
      ],
      '@typescript-eslint/require-await': 'error',
      '@typescript-eslint/switch-exhaustiveness-check': 'error',

      eqeqeq: ['error', 'smart'],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['../../features/*', '@/features/*/*'],
              message:
                'Import across features only through the feature barrel: `@/features/<name>`.',
            },
          ],
        },
      ],
      'no-restricted-globals': [
        'error',
        {
          name: 'process',
          message:
            'Use `env` from `@/shared/lib/env` — `process.env` does not exist in the browser.',
        },
      ],
    },
  },

  // Barrels re-export types and constants alongside components, and main.tsx is
  // the entry point rather than a component module; the Fast Refresh rule has
  // nothing useful to say about either.
  {
    files: [
      'src/**/index.ts',
      'src/**/index.tsx',
      'src/main.tsx',
      'src/shared/components/ui/**/*.tsx',
    ],
    rules: { 'react-refresh/only-export-components': 'off' },
  },

  // ── Build tooling (Node context) ──────────────────────────────────────────
  {
    files: ['*.config.{js,ts}', 'vite.config.ts'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      globals: globals.node,
    },
  },

  // Prettier last: turns off every stylistic rule it would fight with.
  prettier,
);
